"""made foreign key connection - added sqlalchemy ForeignKey() to corresponding fields

Revision ID: 030a8e62c7a0
Revises: f0cf7662eb77
Create Date: 2024-10-16 02:59:02.518191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '030a8e62c7a0'
down_revision: Union[str, None] = 'f0cf7662eb77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'generated_image', 'generated_image_group', ['generated_image_group_id'], ['id'])
    op.create_foreign_key(None, 'generated_image', 'image_generation_job', ['image_generation_job_id'], ['id'])
    op.create_foreign_key(None, 'generated_image', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'generated_image_group', 'generation_request', ['generation_request_id'], ['id'])
    op.create_foreign_key(None, 'generated_image_group', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'generation_request', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'generation_request', 'background', ['background_id'], ['id'])
    op.create_foreign_key(None, 'generation_request', 'hair_variant_model', ['hair_variant_model_id'], ['id'])
    op.create_foreign_key(None, 'generation_request', 'image_resolution', ['image_resolution_id'], ['id'])
    op.create_foreign_key(None, 'hair_design', 'length', ['length_id'], ['id'])
    op.create_foreign_key(None, 'hair_design', 'hair_style', ['hair_style_id'], ['id'])
    op.create_foreign_key(None, 'hair_design_color', 'hair_design', ['hair_design_id'], ['id'])
    op.create_foreign_key(None, 'hair_design_color', 'color', ['color_id'], ['id'])
    op.create_foreign_key(None, 'hair_style', 'length', ['length_id'], ['id'])
    op.create_foreign_key(None, 'hair_style', 'gender', ['gender_id'], ['id'])
    op.create_foreign_key(None, 'hair_style_length', 'hair_style', ['hair_style_id'], ['id'])
    op.create_foreign_key(None, 'hair_style_length', 'length', ['length_id'], ['id'])
    op.create_foreign_key(None, 'hair_variant_model', 'hair_design_color', ['hair_design_color_id'], ['id'])
    op.create_foreign_key(None, 'hair_variant_model', 'lora_model', ['lora_model_id'], ['id'])
    op.create_foreign_key(None, 'image_generation_job', 'generation_request', ['generation_request_id'], ['id'])
    op.create_foreign_key(None, 'posture_and_clothing', 'gender', ['gender_id'], ['id'])
    op.create_foreign_key(None, 'specific_color', 'color', ['color_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'specific_color', type_='foreignkey')
    op.drop_constraint(None, 'posture_and_clothing', type_='foreignkey')
    op.drop_constraint(None, 'image_generation_job', type_='foreignkey')
    op.drop_constraint(None, 'hair_variant_model', type_='foreignkey')
    op.drop_constraint(None, 'hair_variant_model', type_='foreignkey')
    op.drop_constraint(None, 'hair_style_length', type_='foreignkey')
    op.drop_constraint(None, 'hair_style_length', type_='foreignkey')
    op.drop_constraint(None, 'hair_style', type_='foreignkey')
    op.drop_constraint(None, 'hair_style', type_='foreignkey')
    op.drop_constraint(None, 'hair_design_color', type_='foreignkey')
    op.drop_constraint(None, 'hair_design_color', type_='foreignkey')
    op.drop_constraint(None, 'hair_design', type_='foreignkey')
    op.drop_constraint(None, 'hair_design', type_='foreignkey')
    op.drop_constraint(None, 'generation_request', type_='foreignkey')
    op.drop_constraint(None, 'generation_request', type_='foreignkey')
    op.drop_constraint(None, 'generation_request', type_='foreignkey')
    op.drop_constraint(None, 'generation_request', type_='foreignkey')
    op.drop_constraint(None, 'generated_image_group', type_='foreignkey')
    op.drop_constraint(None, 'generated_image_group', type_='foreignkey')
    op.drop_constraint(None, 'generated_image', type_='foreignkey')
    op.drop_constraint(None, 'generated_image', type_='foreignkey')
    op.drop_constraint(None, 'generated_image', type_='foreignkey')
    # ### end Alembic commands ###
