"""(change) added is_custom flag to follow_up_answer table

Revision ID: 09609f46688a
Revises: b854337fd9e5
Create Date: 2025-01-31 14:41:49.216359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09609f46688a'
down_revision: Union[str, None] = 'b854337fd9e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follow_up_answer', sa.Column('is_custom', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('follow_up_answer', 'is_custom')
    # ### end Alembic commands ###
