"""(change) user subscription 에서 user_id unique 해제, is_current_subscription과 묶어서 unique 판단

Revision ID: 0c4ef5b8c55e
Revises: 9e472783a852
Create Date: 2024-12-20 11:56:45.486342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c4ef5b8c55e'
down_revision: Union[str, None] = '9e472783a852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscription', sa.Column('is_current_subscription', sa.Boolean(), nullable=True))
    op.drop_index('ix_user_subscription_user_id', table_name='user_subscription')
    op.create_index(op.f('ix_user_subscription_user_id'), 'user_subscription', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_current_subscription', 'user_subscription', ['user_id', 'is_current_subscription'], deferrable='True', initially='DEFERRED')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_current_subscription', 'user_subscription', type_='unique')
    op.drop_index(op.f('ix_user_subscription_user_id'), table_name='user_subscription')
    op.create_index('ix_user_subscription_user_id', 'user_subscription', ['user_id'], unique=True)
    op.drop_column('user_subscription', 'is_current_subscription')
    # ### end Alembic commands ###
