"""(change) UserSubscription subscription_plan_id unique key remove

Revision ID: 1585a2715c82
Revises: 7ff5cd425048
Create Date: 2024-12-19 10:42:32.289509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1585a2715c82'
down_revision: Union[str, None] = '7ff5cd425048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_subscription_subscription_plan_id', table_name='user_subscription')
    op.create_index(op.f('ix_user_subscription_subscription_plan_id'), 'user_subscription', ['subscription_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_subscription_subscription_plan_id'), table_name='user_subscription')
    op.create_index('ix_user_subscription_subscription_plan_id', 'user_subscription', ['subscription_plan_id'], unique=True)
    # ### end Alembic commands ###
