"""(refactor) app version field change

Revision ID: 1f7eb69dd694
Revises: 9203a59769e9
Create Date: 2025-05-27 05:40:43.704483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f7eb69dd694'
down_revision: Union[str, None] = '9203a59769e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_version', sa.Column('version', sa.String(), nullable=True))
    op.add_column('app_version', sa.Column('is_minimum_version', sa.Boolean(), nullable=True))
    op.add_column('app_version', sa.Column('is_latest_version', sa.Boolean(), nullable=True))
    op.drop_column('app_version', 'store_url')
    op.drop_column('app_version', 'min_version')
    op.drop_column('app_version', 'latest_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_version', sa.Column('latest_version', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('app_version', sa.Column('min_version', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('app_version', sa.Column('store_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('app_version', 'is_latest_version')
    op.drop_column('app_version', 'is_minimum_version')
    op.drop_column('app_version', 'version')
    # ### end Alembic commands ###
