"""(add) generated image / image group - added reported field

Revision ID: 22bfeb3e5edc
Revises: c286cebadb19
Create Date: 2024-12-26 19:24:26.528232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22bfeb3e5edc'
down_revision: Union[str, None] = 'c286cebadb19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_image', sa.Column('reported', sa.Boolean(), nullable=True))
    op.add_column('generated_image_group', sa.Column('reported', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_image_group', 'reported')
    op.drop_column('generated_image', 'reported')
    # ### end Alembic commands ###
