"""(change) unique constraint in user subscription

Revision ID: 2634edcfa7a7
Revises: 22bfeb3e5edc
Create Date: 2025-01-02 13:54:32.605131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2634edcfa7a7'
down_revision: Union[str, None] = '22bfeb3e5edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_active_original_transaction', 'user_subscription', type_='unique')
    op.create_index('uq_active_original_transaction', 'user_subscription', ['original_transaction_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_constraint('uq_active_user', 'user_subscription', type_='unique')
    op.create_index('uq_active_user', 'user_subscription', ['user_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_user', table_name='user_subscription', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_unique_constraint('uq_active_user', 'user_subscription', ['user_id'])
    op.drop_index('uq_active_original_transaction', table_name='user_subscription', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_unique_constraint('uq_active_original_transaction', 'user_subscription', ['original_transaction_id'])
    # ### end Alembic commands ###
