"""(change) is_current field added in token wallet

Revision ID: 26ece0c88c94
Revises: a203f150b1e1
Create Date: 2025-01-02 17:10:55.513117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26ece0c88c94'
down_revision: Union[str, None] = 'a203f150b1e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_wallet', sa.Column('is_current', sa.Boolean(), nullable=True))
    op.drop_index('ix_token_wallet_user_id', table_name='token_wallet')
    op.create_index(op.f('ix_token_wallet_user_id'), 'token_wallet', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_wallet_user_id'), table_name='token_wallet')
    op.create_index('ix_token_wallet_user_id', 'token_wallet', ['user_id'], unique=True)
    op.drop_column('token_wallet', 'is_current')
    # ### end Alembic commands ###
