"""(refactor) uploaded images for training 에 training request id 추가 & request 와 n : m 관계 테이블 제거

Revision ID: 28d11185724e
Revises: c964acbf1ba2
Create Date: 2025-05-23 19:12:41.125745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28d11185724e'
down_revision: Union[str, None] = 'c964acbf1ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_training_request_uploaded_images_training_request_id', table_name='training_request_uploaded_images')
    op.drop_index('ix_training_request_uploaded_images_uploaded_images_for_9381', table_name='training_request_uploaded_images')
    op.drop_table('training_request_uploaded_images')
    op.add_column('uploaded_images_for_training', sa.Column('training_request_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_uploaded_images_for_training_training_request_id'), 'uploaded_images_for_training', ['training_request_id'], unique=False)
    op.create_foreign_key(None, 'uploaded_images_for_training', 'training_request', ['training_request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploaded_images_for_training', type_='foreignkey')
    op.drop_index(op.f('ix_uploaded_images_for_training_training_request_id'), table_name='uploaded_images_for_training')
    op.drop_column('uploaded_images_for_training', 'training_request_id')
    op.create_table('training_request_uploaded_images',
    sa.Column('training_request_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uploaded_images_for_training_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['training_request_id'], ['training_request.id'], name='training_request_uploaded_images_training_request_id_fkey'),
    sa.ForeignKeyConstraint(['uploaded_images_for_training_id'], ['uploaded_images_for_training.id'], name='training_request_uploaded_ima_uploaded_images_for_training_fkey'),
    sa.PrimaryKeyConstraint('id', name='training_request_uploaded_images_pkey')
    )
    op.create_index('ix_training_request_uploaded_images_uploaded_images_for_9381', 'training_request_uploaded_images', ['uploaded_images_for_training_id'], unique=False)
    op.create_index('ix_training_request_uploaded_images_training_request_id', 'training_request_uploaded_images', ['training_request_id'], unique=False)
    # ### end Alembic commands ###
