"""changed model_description field name to lora_model_description in lora_model table

Revision ID: 29ee144da28d
Revises: 8f35c15d687a
Create Date: 2024-10-15 16:50:29.458710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29ee144da28d'
down_revision: Union[str, None] = '8f35c15d687a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lora_model', sa.Column('lora_model_description', sa.String(length=255), nullable=True))
    op.drop_column('lora_model', 'model_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lora_model', sa.Column('model_description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('lora_model', 'lora_model_description')
    # ### end Alembic commands ###
