"""(add) BackgroundForMatting - 배경 제거용 이미지 화소에 맞는 이미지 s3 key 저장 테이블 생성

Revision ID: 2e2ec573f1db
Revises: 806af4cce9b7
Create Date: 2025-02-22 21:04:45.657991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e2ec573f1db'
down_revision: Union[str, None] = '806af4cce9b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_for_matting',
    sa.Column('image_s3_key', sa.String(length=2048), nullable=False),
    sa.Column('image_resolution_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_resolution_id'], ['image_resolution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('image_generation_job', sa.Column('matting_bgr_key', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_generation_job', 'matting_bgr_key')
    op.drop_table('background_for_matting')
    # ### end Alembic commands ###
