"""new tables - example generated image / image group

Revision ID: 2ff9aa15cb17
Revises: 969d1d6d5926
Create Date: 2024-12-09 18:18:16.314391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ff9aa15cb17'
down_revision: Union[str, None] = '969d1d6d5926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example_generated_image_group',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('thumbnail_image_s3_key', sa.String(length=2048), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('example_generated_image',
    sa.Column('s3_key', sa.String(length=1024), nullable=False),
    sa.Column('webui_png_info', sa.String(length=2048), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('example_generated_image_group_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['example_generated_image_group_id'], ['example_generated_image_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_example_generated_image_example_generated_image_group_id'), 'example_generated_image', ['example_generated_image_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_example_generated_image_example_generated_image_group_id'), table_name='example_generated_image')
    op.drop_table('example_generated_image')
    op.drop_table('example_generated_image_group')
    # ### end Alembic commands ###
