"""(add) is_high_res field to generation job

Revision ID: 327b0da99889
Revises: edc830e6a431
Create Date: 2025-08-15 03:58:10.829368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '327b0da99889'
down_revision: Union[str, None] = 'edc830e6a431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_job', sa.Column('is_high_res', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_job', 'is_high_res')
    # ### end Alembic commands ###
