"""(add) custom bgr flag (is_custom_bgr) is added to background table

Revision ID: 368bc14fcfa1
Revises: 41de47a620af
Create Date: 2025-02-22 20:16:20.025084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '368bc14fcfa1'
down_revision: Union[str, None] = '41de47a620af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('background', sa.Column('is_custom_bgr', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('background', 'is_custom_bgr')
    # ### end Alembic commands ###
