"""changed image generation job fields - expires_at, retry_count to not null

Revision ID: 3c92a5d9dd98
Revises: bb59990b9133
Create Date: 2024-10-31 16:41:43.504714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c92a5d9dd98'
down_revision: Union[str, None] = 'bb59990b9133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image_generation_job', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('image_generation_job', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image_generation_job', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('image_generation_job', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
