"""(add & change) image ratio table is added & added is_upscale to image_resolution

Revision ID: 41de47a620af
Revises: 16e6b0f95f9a
Create Date: 2025-02-06 04:22:31.996003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41de47a620af'
down_revision: Union[str, None] = '16e6b0f95f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_ratio',
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('aspect_width', sa.Integer(), nullable=False),
    sa.Column('aspect_height', sa.Integer(), nullable=False),
    sa.Column('image_s3_key', sa.String(length=2048), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('generation_request', sa.Column('image_ratio_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'generation_request', 'image_ratio', ['image_ratio_id'], ['id'])
    op.add_column('image_generation_job', sa.Column('lora_model', sa.String(length=1024), nullable=True))
    op.add_column('image_generation_job', sa.Column('is_upscale', sa.Boolean(), nullable=True))
    op.add_column('image_resolution', sa.Column('is_upscale', sa.Boolean(), nullable=True))
    op.add_column('image_resolution', sa.Column('image_ratio_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'image_resolution', 'image_ratio', ['image_ratio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image_resolution', type_='foreignkey')
    op.drop_column('image_resolution', 'image_ratio_id')
    op.drop_column('image_resolution', 'is_upscale')
    op.drop_column('image_generation_job', 'is_upscale')
    op.drop_column('image_generation_job', 'lora_model')
    op.drop_constraint(None, 'generation_request', type_='foreignkey')
    op.drop_column('generation_request', 'image_ratio_id')
    op.drop_table('image_ratio')
    # ### end Alembic commands ###
