"""add is subscribed to user

Revision ID: 4b88ea5a5ab0
Revises: 2ff9aa15cb17
Create Date: 2024-12-13 05:16:04.550455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b88ea5a5ab0'
down_revision: Union[str, None] = '2ff9aa15cb17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_subscribed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_subscribed')
    # ### end Alembic commands ###
