"""(refactor) app version field change - nullable False

Revision ID: 529fb6f8e2fc
Revises: 1f7eb69dd694
Create Date: 2025-05-27 05:42:07.354703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '529fb6f8e2fc'
down_revision: Union[str, None] = '1f7eb69dd694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_version', 'version',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('app_version', 'is_minimum_version',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('app_version', 'is_latest_version',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_version', 'is_latest_version',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('app_version', 'is_minimum_version',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('app_version', 'version',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
