"""(update) added is_custom_background / last_modified_image_key field to generated image table

Revision ID: 52cb37d3c739
Revises: 2e2ec573f1db
Create Date: 2025-02-26 19:41:39.286625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52cb37d3c739'
down_revision: Union[str, None] = '2e2ec573f1db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_image', sa.Column('last_modified_image_key', sa.String(length=1024), nullable=True))
    op.add_column('generated_image', sa.Column('is_custom_background', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_image', 'is_custom_background')
    op.drop_column('generated_image', 'last_modified_image_key')
    # ### end Alembic commands ###
