"""sqlalchemy orm model 1:1 relation 수정 - 1:1 인 경우 foreign key -> unique true, relation -> uselist false

Revision ID: 56e06b8d78fe
Revises: 1585a2715c82
Create Date: 2024-12-19 11:25:37.956385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56e06b8d78fe'
down_revision: Union[str, None] = '1585a2715c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_token_wallet_user_id', table_name='token_wallet')
    op.create_index(op.f('ix_token_wallet_user_id'), 'token_wallet', ['user_id'], unique=True)
    op.drop_index('ix_token_wallet_user_subscription_id', table_name='token_wallet')
    op.create_index(op.f('ix_token_wallet_user_subscription_id'), 'token_wallet', ['user_subscription_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_wallet_user_subscription_id'), table_name='token_wallet')
    op.create_index('ix_token_wallet_user_subscription_id', 'token_wallet', ['user_subscription_id'], unique=False)
    op.drop_index(op.f('ix_token_wallet_user_id'), table_name='token_wallet')
    op.create_index('ix_token_wallet_user_id', 'token_wallet', ['user_id'], unique=False)
    # ### end Alembic commands ###
