"""(fix)

Revision ID: 5ad8804140c8
Revises: 52cb37d3c739
Create Date: 2025-05-17 09:34:23.370213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ad8804140c8'
down_revision: Union[str, None] = '52cb37d3c739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_generated_image_generation_job_id'), 'generated_image', ['generation_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_image_generation_job_id'), table_name='generated_image')
    # ### end Alembic commands ###
