"""(add) generation request - image denoising strength field removal

Revision ID: 621f05951452
Revises: d77e1c806155
Create Date: 2025-05-22 01:06:05.725493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '621f05951452'
down_revision: Union[str, None] = 'd77e1c806155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_request', 'user_reference_image_denoise_strength')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_request', sa.Column('user_reference_image_denoise_strength', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
