"""added thumbnail_image_s3_key and rating column for image generation group

Revision ID: 68b8d99ba919
Revises: e545cb7909b6
Create Date: 2024-10-24 18:54:43.016142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68b8d99ba919'
down_revision: Union[str, None] = 'e545cb7909b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_image_group', sa.Column('rating', sa.Integer(), nullable=False))
    op.add_column('generated_image_group', sa.Column('thumbnail_image_s3_key', sa.String(length=2048), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_image_group', 'thumbnail_image_s3_key')
    op.drop_column('generated_image_group', 'rating')
    # ### end Alembic commands ###
