"""del - user is subscribed field

Revision ID: 6f1a2a6e6e1c
Revises: 4b88ea5a5ab0
Create Date: 2024-12-16 01:54:11.269522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f1a2a6e6e1c'
down_revision: Union[str, None] = '4b88ea5a5ab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token')
    op.drop_column('user', 'is_subscribed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_subscribed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('token', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
