"""(remove) user_id, is_current unique constraint - token wallet

Revision ID: 72abdce01c37
Revises: e42a13803223
Create Date: 2025-01-04 03:50:52.754847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72abdce01c37'
down_revision: Union[str, None] = 'e42a13803223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_current_user_tokenwallet', table_name='token_wallet', postgresql_where='(is_current = true)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_current_user_tokenwallet', 'token_wallet', ['user_id'], unique=True, postgresql_where='(is_current = true)')
    # ### end Alembic commands ###
