"""changing updated_at onupdate value type

Revision ID: 7ba05d48366c
Revises: fb1a2386b264
Create Date: 2024-12-01 05:09:20.268902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba05d48366c'
down_revision: Union[str, None] = 'fb1a2386b264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
