"""(change) original_transaction_id unique 해제, user_id, is_current_subscription과 묶어서 unique 판단

Revision ID: 7bba0fc355b3
Revises: 0c4ef5b8c55e
Create Date: 2024-12-20 14:52:10.248003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bba0fc355b3'
down_revision: Union[str, None] = '0c4ef5b8c55e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_current_subscription', 'user_subscription', type_='unique')
    op.drop_index('ix_user_subscription_original_transaction_id', table_name='user_subscription')
    op.create_index(op.f('ix_user_subscription_original_transaction_id'), 'user_subscription', ['original_transaction_id'], unique=False)
    op.create_unique_constraint('uq_user_original_transaction_current', 'user_subscription', ['original_transaction_id', 'user_id', 'is_current_subscription'], deferrable='True', initially='DEFERRED')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_original_transaction_current', 'user_subscription', type_='unique')
    op.drop_index(op.f('ix_user_subscription_original_transaction_id'), table_name='user_subscription')
    op.create_index('ix_user_subscription_original_transaction_id', 'user_subscription', ['original_transaction_id'], unique=True)
    op.create_unique_constraint('uq_user_current_subscription', 'user_subscription', ['user_id', 'is_current_subscription'])
    # ### end Alembic commands ###
