"""changing user index key - unique contraints

Revision ID: 7c194ccf089d
Revises: 4953cb42b30d
Create Date: 2024-12-02 10:10:55.770010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c194ccf089d'
down_revision: Union[str, None] = '4953cb42b30d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_provider_social_id', table_name='user')
    op.drop_constraint('uix_provider_social_id', 'user', type_='unique')
    op.create_index('idx_provider_social_id_active', 'user', ['provider', 'social_id'], unique=True, postgresql_where=sa.text('deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_provider_social_id_active', table_name='user', postgresql_where=sa.text('deleted = false'))
    op.create_unique_constraint('uix_provider_social_id', 'user', ['provider', 'social_id'])
    op.create_index('idx_provider_social_id', 'user', ['provider', 'social_id'], unique=False)
    # ### end Alembic commands ###
