"""(add) custom bgr flag (is_custom_bgr) is added to image generation job table

Revision ID: 806af4cce9b7
Revises: 368bc14fcfa1
Create Date: 2025-02-22 20:23:49.975882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '806af4cce9b7'
down_revision: Union[str, None] = '368bc14fcfa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_generation_job', sa.Column('is_custom_bgr', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_generation_job', 'is_custom_bgr')
    # ### end Alembic commands ###
