"""added order field in models

Revision ID: 8f35c15d687a
Revises: 
Create Date: 2024-10-15 16:46:55.793606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f35c15d687a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background',
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('prompt', sa.String(length=1024), nullable=False),
    sa.Column('image_s3_key', sa.String(length=2048), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_image',
    sa.Column('s3_key', sa.String(length=1024), nullable=False),
    sa.Column('webui_png_info', sa.String(length=2048), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('generated_image_group_id', sa.Integer(), nullable=True),
    sa.Column('image_generation_job_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_image_generated_image_group_id'), 'generated_image', ['generated_image_group_id'], unique=False)
    op.create_index(op.f('ix_generated_image_user_id'), 'generated_image', ['user_id'], unique=False)
    op.create_table('generated_image_group',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('generation_request_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_image_group_generation_request_id'), 'generated_image_group', ['generation_request_id'], unique=False)
    op.create_index(op.f('ix_generated_image_group_user_id'), 'generated_image_group', ['user_id'], unique=False)
    op.create_table('generation_request',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hair_variant_model_id', sa.Integer(), nullable=True),
    sa.Column('background_id', sa.Integer(), nullable=True),
    sa.Column('image_resolution_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_request_user_id'), 'generation_request', ['user_id'], unique=False)
    op.create_table('image_generation_job',
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='generationstatusenum'), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('prompt', sa.String(length=1024), nullable=False),
    sa.Column('distilled_cfg_scale', sa.Float(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('generation_request_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_generation_job_generation_request_id'), 'image_generation_job', ['generation_request_id'], unique=False)
    op.create_table('image_resolution',
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('aspect_width', sa.Integer(), nullable=False),
    sa.Column('aspect_height', sa.Integer(), nullable=False),
    sa.Column('image_s3_key', sa.String(length=2048), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posture_and_clothing',
    sa.Column('prompt', sa.String(length=1024), nullable=False),
    sa.Column('gender_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posture_and_clothing_gender_id'), 'posture_and_clothing', ['gender_id'], unique=False)
    op.create_table('user',
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('token', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.add_column('lora_model', sa.Column('model_description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lora_model', 'model_description')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_posture_and_clothing_gender_id'), table_name='posture_and_clothing')
    op.drop_table('posture_and_clothing')
    op.drop_table('image_resolution')
    op.drop_index(op.f('ix_image_generation_job_generation_request_id'), table_name='image_generation_job')
    op.drop_table('image_generation_job')
    op.drop_index(op.f('ix_generation_request_user_id'), table_name='generation_request')
    op.drop_table('generation_request')
    op.drop_index(op.f('ix_generated_image_group_user_id'), table_name='generated_image_group')
    op.drop_index(op.f('ix_generated_image_group_generation_request_id'), table_name='generated_image_group')
    op.drop_table('generated_image_group')
    op.drop_index(op.f('ix_generated_image_user_id'), table_name='generated_image')
    op.drop_index(op.f('ix_generated_image_generated_image_group_id'), table_name='generated_image')
    op.drop_table('generated_image')
    op.drop_table('background')
    # ### end Alembic commands ###
