"""add title column in generated image gruop

Revision ID: 9115a9d82754
Revises: 1d989b07e034
Create Date: 2024-11-05 01:07:23.425551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9115a9d82754'
down_revision: Union[str, None] = '1d989b07e034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_image_group', sa.Column('title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_image_group', 'title')
    # ### end Alembic commands ###
