"""changing field deleted to not null

Revision ID: 95573e49062c
Revises: 6a6233450596
Create Date: 2024-10-30 14:24:53.933072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95573e49062c'
down_revision: Union[str, None] = '6a6233450596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generated_image', 'deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('generated_image_group', 'deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generated_image_group', 'deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('generated_image', 'deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
