"""(change) is_current field in user subscription

Revision ID: a203f150b1e1
Revises: 2634edcfa7a7
Create Date: 2025-01-02 15:31:29.775797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a203f150b1e1'
down_revision: Union[str, None] = '2634edcfa7a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscription', sa.Column('is_current', sa.Boolean(), nullable=True))
    op.drop_index('uq_active_original_transaction', table_name='user_subscription', postgresql_where="(status = 'ACTIVE'::subscriptionstatus)")
    op.drop_index('uq_active_user', table_name='user_subscription', postgresql_where="(status = 'ACTIVE'::subscriptionstatus)")
    op.create_index('uq_current_original_transaction', 'user_subscription', ['original_transaction_id'], unique=True, postgresql_where=sa.text('is_current = TRUE'))
    op.create_index('uq_current_user', 'user_subscription', ['user_id'], unique=True, postgresql_where=sa.text('is_current = TRUE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_current_user', table_name='user_subscription', postgresql_where=sa.text('is_current = TRUE'))
    op.drop_index('uq_current_original_transaction', table_name='user_subscription', postgresql_where=sa.text('is_current = TRUE'))
    op.create_index('uq_active_user', 'user_subscription', ['user_id'], unique=True, postgresql_where="(status = 'ACTIVE'::subscriptionstatus)")
    op.create_index('uq_active_original_transaction', 'user_subscription', ['original_transaction_id'], unique=True, postgresql_where="(status = 'ACTIVE'::subscriptionstatus)")
    op.drop_column('user_subscription', 'is_current')
    # ### end Alembic commands ###
