"""deleted is_published field due to removal of hair model option publishing logic

Revision ID: a9eb10f254e3
Revises: 
Create Date: 2024-10-22 15:11:54.342225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9eb10f254e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gender', 'is_published')
    op.drop_column('hair_design_color', 'is_published')
    op.drop_column('hair_style', 'is_published')
    op.drop_column('hair_style_length', 'is_published')
    op.drop_column('hair_variant_model', 'is_published')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hair_variant_model', sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('hair_style_length', sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('hair_style', sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('hair_design_color', sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('gender', sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
