"""(change) user account deletion survey table update

Revision ID: b854337fd9e5
Revises: 72abdce01c37
Create Date: 2025-01-31 02:46:16.534491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b854337fd9e5'
down_revision: Union[str, None] = '72abdce01c37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_deletion_survey_answer')
    op.drop_table('deletion_survey_answer')
    op.drop_table('deletion_survey_question')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deletion_survey_question',
    sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('deletion_survey_question_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='deletion_survey_question_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_deletion_survey_answer',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['deletion_survey_answer.id'], name='user_deletion_survey_answer_answer_id_fkey'),
    sa.ForeignKeyConstraint(['question_id'], ['deletion_survey_question.id'], name='user_deletion_survey_answer_question_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_deletion_survey_answer_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_deletion_survey_answer_pkey')
    )
    op.create_table('deletion_survey_answer',
    sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['deletion_survey_question.id'], name='deletion_survey_answer_question_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='deletion_survey_answer_pkey')
    )
    # ### end Alembic commands ###
