"""(add) training job - thumbnail prompt / width / height

Revision ID: b985718ce6f3
Revises: fbd1bc083137
Create Date: 2025-05-25 03:59:07.896912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b985718ce6f3'
down_revision: Union[str, None] = 'fbd1bc083137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_job', sa.Column('thumbnail_s3_key', sa.String(), nullable=True))
    op.add_column('training_job', sa.Column('thumbnail_width', sa.Integer(), nullable=True))
    op.add_column('training_job', sa.Column('thumbnail_height', sa.Integer(), nullable=True))
    op.add_column('training_job', sa.Column('thumbnail_prompt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_job', 'thumbnail_prompt')
    op.drop_column('training_job', 'thumbnail_height')
    op.drop_column('training_job', 'thumbnail_width')
    op.drop_column('training_job', 'thumbnail_s3_key')
    # ### end Alembic commands ###
