"""(refac) renaming credit -> token in user_purchase / store_product talbels

Revision ID: ba1df80e11a9
Revises: 30aa88cacd47
Create Date: 2025-08-29 02:18:13.685846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba1df80e11a9'
down_revision: Union[str, None] = '30aa88cacd47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_product', sa.Column('token_amount', sa.Integer(), nullable=False))
    op.drop_column('store_product', 'credit_amount')
    op.add_column('user_purchase', sa.Column('received_token_amount', sa.Integer(), nullable=False))
    op.drop_column('user_purchase', 'received_credit_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_purchase', sa.Column('received_credit_amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user_purchase', 'received_token_amount')
    op.add_column('store_product', sa.Column('credit_amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('store_product', 'token_amount')
    # ### end Alembic commands ###
