"""added new fields to image generation job model to track mq message ttl / retry request

Revision ID: bb59990b9133
Revises: 95573e49062c
Create Date: 2024-10-31 16:34:08.457982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb59990b9133'
down_revision: Union[str, None] = '95573e49062c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_generation_job', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('image_generation_job', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.drop_column('image_generation_job', 'requested_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_generation_job', sa.Column('requested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('image_generation_job', 'retry_count')
    op.drop_column('image_generation_job', 'expires_at')
    # ### end Alembic commands ###
