"""(change) user subscription field fix

Revision ID: c286cebadb19
Revises: cece371309db
Create Date: 2024-12-25 22:24:44.131052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c286cebadb19'
down_revision: Union[str, None] = 'cece371309db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscription', sa.Column('initial_purchase_date', sa.DateTime(), nullable=True))
    op.drop_constraint('uq_user_original_transaction_current', 'user_subscription', type_='unique')
    op.create_unique_constraint('uq_active_original_transaction', 'user_subscription', ['original_transaction_id'], deferrable='True', initially='DEFERRED')
    op.create_unique_constraint('uq_active_user', 'user_subscription', ['user_id'], deferrable='True', initially='DEFERRED')
    op.drop_column('user_subscription', 'canceled_at')
    op.drop_column('user_subscription', 'is_current_subscription')
    op.drop_column('user_subscription', 'auto_renew_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscription', sa.Column('auto_renew_status', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user_subscription', sa.Column('is_current_subscription', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user_subscription', sa.Column('canceled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_active_user', 'user_subscription', type_='unique')
    op.drop_constraint('uq_active_original_transaction', 'user_subscription', type_='unique')
    op.create_unique_constraint('uq_user_original_transaction_current', 'user_subscription', ['original_transaction_id', 'user_id', 'is_current_subscription'])
    op.drop_column('user_subscription', 'initial_purchase_date')
    # ### end Alembic commands ###
