"""(refactor) GeneraionRequest - generation_result -> result

Revision ID: c6d2494af8a8
Revises: 5ad8804140c8
Create Date: 2025-05-21 01:09:00.463180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6d2494af8a8'
down_revision: Union[str, None] = '5ad8804140c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_request', sa.Column('result', sa.Enum('PENDING', 'SUCCEED', 'FAILED', 'CANCELED', name='generationrequestresult'), nullable=True))
    op.drop_column('generation_request', 'generation_result')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_request', sa.Column('generation_result', postgresql.ENUM('PENDING', 'SUCCEED', 'FAILED', 'CANCELED', name='generationrequestresult'), autoincrement=False, nullable=False))
    op.drop_column('generation_request', 'result')
    # ### end Alembic commands ###
