"""(add) user hair style status 도입 - nullable False

Revision ID: c964acbf1ba2
Revises: f3c7caaae951
Create Date: 2025-05-23 16:05:21.341006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c964acbf1ba2'
down_revision: Union[str, None] = 'f3c7caaae951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_job', 'thumbnail_creation_failure_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_hair_style', 'status',
               existing_type=postgresql.ENUM('PENDING', 'REGISTERED', 'FAILED', 'DELETED', name='userhairstylestatus'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_hair_style', 'status',
               existing_type=postgresql.ENUM('PENDING', 'REGISTERED', 'FAILED', 'DELETED', name='userhairstylestatus'),
               nullable=True)
    op.alter_column('training_job', 'thumbnail_creation_failure_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
