"""(add) unique contraint to token wallet - user_id & is_current==True

Revision ID: cb4593e4ff11
Revises: a108ff0c9580
Create Date: 2025-01-03 15:49:32.740476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb4593e4ff11'
down_revision: Union[str, None] = 'a108ff0c9580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_current_user_tokenwallet', 'token_wallet', ['user_id'], unique=True, postgresql_where=sa.text('is_current = TRUE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_current_user_tokenwallet', table_name='token_wallet', postgresql_where=sa.text('is_current = TRUE'))
    # ### end Alembic commands ###
