"""(add) generation request - user_reference_image_similarity enum

Revision ID: d77e1c806155
Revises: 083129fce099
Create Date: 2025-05-22 00:56:53.897182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd77e1c806155'
down_revision: Union[str, None] = '083129fce099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_request', sa.Column('user_reference_image_similarity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='referenceimagesimilarity'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_request', 'user_reference_image_similarity')
    # ### end Alembic commands ###
