"""(remove) user_id, is_current unique constraint - user sub

Revision ID: e42a13803223
Revises: 202bb3ce125f
Create Date: 2025-01-04 03:49:06.249761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e42a13803223'
down_revision: Union[str, None] = '202bb3ce125f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_current_user', table_name='user_subscription', postgresql_where='(is_current = true)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_current_user', 'user_subscription', ['user_id'], unique=True, postgresql_where='(is_current = true)')
    # ### end Alembic commands ###
