"""added order to hair model scene entities

Revision ID: e545cb7909b6
Revises: a9eb10f254e3
Create Date: 2024-10-22 16:40:06.783804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e545cb7909b6'
down_revision: Union[str, None] = 'a9eb10f254e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('background', sa.Column('order', sa.Integer(), nullable=True))
    op.add_column('image_resolution', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_resolution', 'order')
    op.drop_column('background', 'order')
    # ### end Alembic commands ###
