"""(add) user hair style - request id 갖고 있도록 함

Revision ID: e6fd46087c1b
Revises: ee34903f1d9f
Create Date: 2025-05-25 03:29:06.039643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6fd46087c1b'
down_revision: Union[str, None] = 'ee34903f1d9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_hair_style', sa.Column('training_request_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_hair_style', 'training_request', ['training_request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_hair_style', type_='foreignkey')
    op.drop_column('user_hair_style', 'training_request_id')
    # ### end Alembic commands ###
