"""added user social auth info to user model

Revision ID: e72b0ea3787e
Revises: 68b8d99ba919
Create Date: 2024-10-28 23:44:08.240503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e72b0ea3787e'
down_revision: Union[str, None] = '68b8d99ba919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('user', sa.Column('provider', sa.String(length=20), nullable=False))
    op.add_column('user', sa.Column('provider', sa.String(length=20), nullable=True))
    op.execute("UPDATE \"user\" SET provider = 'local' WHERE provider IS NULL")

    op.add_column('user', sa.Column('social_id', sa.String(length=255), nullable=True))
    op.execute("UPDATE \"user\" SET social_id= 'local' WHERE social_id IS NULL")
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=320),
               existing_nullable=False)
    op.drop_index('ix_user_email', table_name='user')
    op.create_index('idx_provider_social_id', 'user', ['provider', 'social_id'], unique=False)
    op.create_unique_constraint('uix_provider_social_id', 'user', ['provider', 'social_id'])
    op.alter_column('user', 'provider',
                    existing_type=sa.String(length=20),
                    nullable=False)
    op.alter_column('user', 'social_id',
                    existing_type=sa.String(length=255),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_provider_social_id', 'user', type_='unique')
    op.drop_index('idx_provider_social_id', table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.alter_column('user', 'email',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('user', 'social_id')
    op.drop_column('user', 'provider')
    # ### end Alembic commands ###
