"""(change) plan store type to not nullalbe

Revision ID: e856e5aa0edf
Revises: 56e06b8d78fe
Create Date: 2024-12-19 14:35:50.179642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e856e5aa0edf'
down_revision: Union[str, None] = '56e06b8d78fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription_plan', 'store_type',
               existing_type=postgresql.ENUM('APP_STORE', 'PLAY_STORE', name='storetype'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription_plan', 'store_type',
               existing_type=postgresql.ENUM('APP_STORE', 'PLAY_STORE', name='storetype'),
               nullable=True)
    # ### end Alembic commands ###
