"""(refactor) UploadedImagesForTraining -> UploadedImageForTraining

Revision ID: eb64a86f0afc
Revises: 28d11185724e
Create Date: 2025-05-23 19:29:48.935493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb64a86f0afc'
down_revision: Union[str, None] = '28d11185724e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_image_for_training',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('training_request_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['training_request_id'], ['training_request.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_image_for_training_training_request_id'), 'uploaded_image_for_training', ['training_request_id'], unique=False)
    op.create_index(op.f('ix_uploaded_image_for_training_user_id'), 'uploaded_image_for_training', ['user_id'], unique=False)
    op.drop_index('ix_uploaded_images_for_training_training_request_id', table_name='uploaded_images_for_training')
    op.drop_index('ix_uploaded_images_for_training_user_id', table_name='uploaded_images_for_training')
    op.drop_table('uploaded_images_for_training')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_images_for_training',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('s3_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('training_request_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['training_request_id'], ['training_request.id'], name='uploaded_images_for_training_training_request_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='uploaded_images_for_training_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='uploaded_images_for_training_pkey')
    )
    op.create_index('ix_uploaded_images_for_training_user_id', 'uploaded_images_for_training', ['user_id'], unique=False)
    op.create_index('ix_uploaded_images_for_training_training_request_id', 'uploaded_images_for_training', ['training_request_id'], unique=False)
    op.drop_index(op.f('ix_uploaded_image_for_training_user_id'), table_name='uploaded_image_for_training')
    op.drop_index(op.f('ix_uploaded_image_for_training_training_request_id'), table_name='uploaded_image_for_training')
    op.drop_table('uploaded_image_for_training')
    # ### end Alembic commands ###
