"""(refac) generation job to have lora model name and lora model s3 key whether user custom style or not

Revision ID: edc830e6a431
Revises: 529fb6f8e2fc
Create Date: 2025-06-26 11:43:48.853131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edc830e6a431'
down_revision: Union[str, None] = '529fb6f8e2fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. 새로운 컬럼들 추가
    op.add_column('generation_job', sa.Column('lora_model_s3_key', sa.String(length=1024), nullable=True))
    op.add_column('generation_job', sa.Column('lora_model_name', sa.String(length=1024), nullable=True))
    
    # 2. 기존 데이터를 새로운 컬럼으로 복사
    connection = op.get_bind()
    
    # user_hair_lora_model_s3_key -> lora_model_s3_key로 복사
    connection.execute(sa.text("""
        UPDATE generation_job 
        SET lora_model_s3_key = user_hair_lora_model_s3_key 
        WHERE user_hair_lora_model_s3_key IS NOT NULL
    """))
    
    # hair_lora_model_name -> lora_model_name으로 복사
    connection.execute(sa.text("""
        UPDATE generation_job 
        SET lora_model_name = hair_lora_model_name 
        WHERE hair_lora_model_name IS NOT NULL
    """))
    
    # 3. 기존 컬럼들 삭제
    op.drop_column('generation_job', 'hair_lora_model_name')
    op.drop_column('generation_job', 'user_hair_lora_model_s3_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. 기존 컬럼들 다시 추가
    op.add_column('generation_job', sa.Column('user_hair_lora_model_s3_key', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('generation_job', sa.Column('hair_lora_model_name', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    
    # 2. 데이터를 기존 컬럼으로 복사
    connection = op.get_bind()
    
    # lora_model_s3_key -> user_hair_lora_model_s3_key로 복사
    connection.execute(sa.text("""
        UPDATE generation_job 
        SET user_hair_lora_model_s3_key = lora_model_s3_key 
        WHERE lora_model_s3_key IS NOT NULL
    """))
    
    # lora_model_name -> hair_lora_model_name으로 복사  
    connection.execute(sa.text("""
        UPDATE generation_job 
        SET hair_lora_model_name = lora_model_name 
        WHERE lora_model_name IS NOT NULL
    """))
    
    # 3. 새로운 컬럼들 삭제
    op.drop_column('generation_job', 'lora_model_name')
    op.drop_column('generation_job', 'lora_model_s3_key')
    # ### end Alembic commands ###
