"""added new columns (supported_style, supported lengths, supported colors in lora model table

Revision ID: f0cf7662eb77
Revises: 29ee144da28d
Create Date: 2024-10-15 16:59:54.049344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0cf7662eb77'
down_revision: Union[str, None] = '29ee144da28d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lora_model', sa.Column('supported_style', sa.String(length=255), nullable=True))
    op.add_column('lora_model', sa.Column('supported_lengths', sa.String(length=255), nullable=True))
    op.add_column('lora_model', sa.Column('supported_colors', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lora_model', 'supported_colors')
    op.drop_column('lora_model', 'supported_lengths')
    op.drop_column('lora_model', 'supported_style')
    # ### end Alembic commands ###
