"""(add) user hair style status 도입

Revision ID: f3c7caaae951
Revises: 621f05951452
Create Date: 2025-05-23 16:04:24.122357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c7caaae951'
down_revision: Union[str, None] = '621f05951452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_job', sa.Column('thumbnail_creation_failure_count', sa.Integer(), nullable=True))
    op.add_column('training_job', sa.Column('thumbnail_creation_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_hair_style', sa.Column('status', sa.Enum('PENDING', 'REGISTERED', 'FAILED', 'DELETED', name='userhairstylestatus'), nullable=True))
    op.alter_column('user_hair_style', 'user_hair_style_lora_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_hair_style', 'user_hair_style_lora_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user_hair_style', 'status')
    op.drop_column('training_job', 'thumbnail_creation_expires_at')
    op.drop_column('training_job', 'thumbnail_creation_failure_count')
    # ### end Alembic commands ###
