"""(add) user hair style - request id 갖고 있도록 함 - nullable=False

Revision ID: fbd1bc083137
Revises: e6fd46087c1b
Create Date: 2025-05-25 03:31:14.949025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbd1bc083137'
down_revision: Union[str, None] = 'e6fd46087c1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_hair_style', 'training_request_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_hair_style', 'training_request_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
